Texture2D<float4> tex[128] : register(t0); // 128 textures, 0-127

sampler samp : register(s0);

float4 main(float4 color : Color, uint id : TextureID, float2 texCoord : TexCoord) : SV_Target
{
    switch (id)
    {
        case  0: return tex[  0].Sample(samp, texCoord) * color;
        case  1: return tex[  1].Sample(samp, texCoord) * color;
        case  2: return tex[  2].Sample(samp, texCoord) * color;
        case  3: return tex[  3].Sample(samp, texCoord) * color;
        case  4: return tex[  4].Sample(samp, texCoord) * color;
        case  5: return tex[  5].Sample(samp, texCoord) * color;
        case  6: return tex[  6].Sample(samp, texCoord) * color;
        case  7: return tex[  7].Sample(samp, texCoord) * color;
        case  8: return tex[  8].Sample(samp, texCoord) * color;
        case  9: return tex[  9].Sample(samp, texCoord) * color;
        case 10: return tex[ 10].Sample(samp, texCoord) * color;
        case 11: return tex[ 11].Sample(samp, texCoord) * color;
        case 12: return tex[ 12].Sample(samp, texCoord) * color;
        case 13: return tex[ 13].Sample(samp, texCoord) * color;
        case 14: return tex[ 14].Sample(samp, texCoord) * color;
        case 15: return tex[ 15].Sample(samp, texCoord) * color;
        case 16: return tex[ 16].Sample(samp, texCoord) * color;
        case 17: return tex[ 17].Sample(samp, texCoord) * color;
        case 18: return tex[ 18].Sample(samp, texCoord) * color;
        case 19: return tex[ 19].Sample(samp, texCoord) * color;
        case 20: return tex[ 20].Sample(samp, texCoord) * color;
        case 21: return tex[ 21].Sample(samp, texCoord) * color;
        case 22: return tex[ 22].Sample(samp, texCoord) * color;
        case 23: return tex[ 23].Sample(samp, texCoord) * color;
        case 24: return tex[ 24].Sample(samp, texCoord) * color;
        case 25: return tex[ 25].Sample(samp, texCoord) * color;
        case 26: return tex[ 26].Sample(samp, texCoord) * color;
        case 27: return tex[ 27].Sample(samp, texCoord) * color;
        case 28: return tex[ 28].Sample(samp, texCoord) * color;
        case 29: return tex[ 29].Sample(samp, texCoord) * color;
        case 30: return tex[ 30].Sample(samp, texCoord) * color;
        case 31: return tex[ 31].Sample(samp, texCoord) * color;
        case 32: return tex[ 32].Sample(samp, texCoord) * color;
        case 33: return tex[ 33].Sample(samp, texCoord) * color;
        case 34: return tex[ 34].Sample(samp, texCoord) * color;
        case 35: return tex[ 35].Sample(samp, texCoord) * color;
        case 36: return tex[ 36].Sample(samp, texCoord) * color;
        case 37: return tex[ 37].Sample(samp, texCoord) * color;
        case 38: return tex[ 38].Sample(samp, texCoord) * color;
        case 39: return tex[ 39].Sample(samp, texCoord) * color;
        case 40: return tex[ 40].Sample(samp, texCoord) * color;
        case 41: return tex[ 41].Sample(samp, texCoord) * color;
        case 42: return tex[ 42].Sample(samp, texCoord) * color;
        case 43: return tex[ 43].Sample(samp, texCoord) * color;
        case 44: return tex[ 44].Sample(samp, texCoord) * color;
        case 45: return tex[ 45].Sample(samp, texCoord) * color;
        case 46: return tex[ 46].Sample(samp, texCoord) * color;
        case 47: return tex[ 47].Sample(samp, texCoord) * color;
        case 48: return tex[ 48].Sample(samp, texCoord) * color;
        case 49: return tex[ 49].Sample(samp, texCoord) * color;
        case 50: return tex[ 50].Sample(samp, texCoord) * color;
        case 51: return tex[ 51].Sample(samp, texCoord) * color;
        case 52: return tex[ 52].Sample(samp, texCoord) * color;
        case 53: return tex[ 53].Sample(samp, texCoord) * color;
        case 54: return tex[ 54].Sample(samp, texCoord) * color;
        case 55: return tex[ 55].Sample(samp, texCoord) * color;
        case 56: return tex[ 56].Sample(samp, texCoord) * color;
        case 57: return tex[ 57].Sample(samp, texCoord) * color;
        case 58: return tex[ 58].Sample(samp, texCoord) * color;
        case 59: return tex[ 59].Sample(samp, texCoord) * color;
        case 60: return tex[ 60].Sample(samp, texCoord) * color;
        case 61: return tex[ 61].Sample(samp, texCoord) * color;
        case 62: return tex[ 62].Sample(samp, texCoord) * color;
        case 63: return tex[ 63].Sample(samp, texCoord) * color;
        case 64: return tex[ 64].Sample(samp, texCoord) * color;
        case 65: return tex[ 65].Sample(samp, texCoord) * color;
        case 66: return tex[ 66].Sample(samp, texCoord) * color;
        case 67: return tex[ 67].Sample(samp, texCoord) * color;
        case 68: return tex[ 68].Sample(samp, texCoord) * color;
        case 69: return tex[ 69].Sample(samp, texCoord) * color;
        case 70: return tex[ 70].Sample(samp, texCoord) * color;
        case 71: return tex[ 71].Sample(samp, texCoord) * color;
        case 72: return tex[ 72].Sample(samp, texCoord) * color;
        case 73: return tex[ 73].Sample(samp, texCoord) * color;
        case 74: return tex[ 74].Sample(samp, texCoord) * color;
        case 75: return tex[ 75].Sample(samp, texCoord) * color;
        case 76: return tex[ 76].Sample(samp, texCoord) * color;
        case 77: return tex[ 77].Sample(samp, texCoord) * color;
        case 78: return tex[ 78].Sample(samp, texCoord) * color;
        case 79: return tex[ 79].Sample(samp, texCoord) * color;
        case 80: return tex[ 80].Sample(samp, texCoord) * color;
        case 81: return tex[ 81].Sample(samp, texCoord) * color;
        case 82: return tex[ 82].Sample(samp, texCoord) * color;
        case 83: return tex[ 83].Sample(samp, texCoord) * color;
        case 84: return tex[ 84].Sample(samp, texCoord) * color;
        case 85: return tex[ 85].Sample(samp, texCoord) * color;
        case 86: return tex[ 86].Sample(samp, texCoord) * color;
        case 87: return tex[ 87].Sample(samp, texCoord) * color;
        case 88: return tex[ 88].Sample(samp, texCoord) * color;
        case 89: return tex[ 89].Sample(samp, texCoord) * color;
        case 90: return tex[ 90].Sample(samp, texCoord) * color;
        case 91: return tex[ 91].Sample(samp, texCoord) * color;
        case 92: return tex[ 92].Sample(samp, texCoord) * color;
        case 93: return tex[ 93].Sample(samp, texCoord) * color;
        case 94: return tex[ 94].Sample(samp, texCoord) * color;
        case 95: return tex[ 95].Sample(samp, texCoord) * color;
        case 96: return tex[ 96].Sample(samp, texCoord) * color;
        case 97: return tex[ 97].Sample(samp, texCoord) * color;
        case 98: return tex[ 98].Sample(samp, texCoord) * color;
        case 99: return tex[ 99].Sample(samp, texCoord) * color;
        case 100: return tex[100].Sample(samp, texCoord) * color;
        case 101: return tex[101].Sample(samp, texCoord) * color;
        case 102: return tex[102].Sample(samp, texCoord) * color;
        case 103: return tex[103].Sample(samp, texCoord) * color;
        case 104: return tex[104].Sample(samp, texCoord) * color;
        case 105: return tex[105].Sample(samp, texCoord) * color;
        case 106: return tex[106].Sample(samp, texCoord) * color;
        case 107: return tex[107].Sample(samp, texCoord) * color;
        case 108: return tex[108].Sample(samp, texCoord) * color;
        case 109: return tex[109].Sample(samp, texCoord) * color;
        case 110: return tex[110].Sample(samp, texCoord) * color;
        case 111: return tex[111].Sample(samp, texCoord) * color;
        case 112: return tex[112].Sample(samp, texCoord) * color;
        case 113: return tex[113].Sample(samp, texCoord) * color;
        case 114: return tex[114].Sample(samp, texCoord) * color;
        case 115: return tex[115].Sample(samp, texCoord) * color;
        case 116: return tex[116].Sample(samp, texCoord) * color;
        case 117: return tex[117].Sample(samp, texCoord) * color;
        case 118: return tex[118].Sample(samp, texCoord) * color;
        case 119: return tex[119].Sample(samp, texCoord) * color;
        case 120: return tex[120].Sample(samp, texCoord) * color;
        case 121: return tex[121].Sample(samp, texCoord) * color;
        case 122: return tex[122].Sample(samp, texCoord) * color;
        case 123: return tex[123].Sample(samp, texCoord) * color;
        case 124: return tex[124].Sample(samp, texCoord) * color;
        case 125: return tex[125].Sample(samp, texCoord) * color;
        case 126: return tex[126].Sample(samp, texCoord) * color;
        case 127: return tex[127].Sample(samp, texCoord) * color;
        default: return color;
    }
}